import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
const inter = Inter({ subsets: ['latin'] })
 
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <div
      className={`${inter.className} min-h-screen flex flex-col justify-between bg-mainBackground`}
    >
     <Navbar />  
      <main className='flex-grow'>{children}</main>
    
         <Footer />
      
    </div>
  )
}